<a href="https://colab.research.google.com/github/devanshi311/JAVASCRIPT/blob/main/00_day_pytorchLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Helll!!!")

Helll!!!


In [ ]:
!nvidia-smi

Wed Jan 17 08:49:43 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   47C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


In [ ]:
#intoduction to tensor

In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#TENSER

TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [2,3,7]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [2, 3, 7]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

#Random tensors
why random tensors?
Random tensors are important the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

start with random numbers -> Look at data -> update random numbers  ->look at data -> update random numbers

In [ ]:
#Create a random tensor of size
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8735, 0.5682, 0.7676, 0.0077],
        [0.0813, 0.8853, 0.1871, 0.0389],
        [0.7847, 0.2311, 0.3510, 0.7104]])

In [ ]:
#Create a random tensor of size
random_tensor = torch.rand(1,1,10)
random_tensor

tensor([[[0.9793, 0.1115, 0.3280, 0.1148, 0.6065, 0.7775, 0.3530, 0.9172,
          0.2433, 0.9187]]])

In [ ]:
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)