<a href="https://colab.research.google.com/github/devanshi311/Pytorch-Learning/blob/main/02_day_pytorchLearing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [ ]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.4948, 0.8469, 0.7843, 0.0661],
        [0.9555, 0.5071, 0.0241, 0.0656],
        [0.8132, 0.9965, 0.9345, 0.0458]])

In [ ]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
x = torch.arange(start=0, end=11, step=1)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
ten_zeros = torch.zeros_like(input=x)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor Datatypes

**Note:** Tensor Datatypes is one of the 3 big errors you'll run into with pytorch & deep learing:

1.   Tensors not right datatype

2.  Tensors not right shape

3.   Tensors not on the right device







  



In [ ]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)#whether or not to trac gradients with this tensors oprations
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int64)
int_32_tensor

tensor([3, 6, 9])

In [ ]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
long_tensor = torch.tensor([3,6,9], dtype=torch.long)
long_tensor

tensor([3, 6, 9])

In [ ]:
float_32_tensor*long_tensor

tensor([ 9., 36., 81.])

# Getting Information from tensors


1. Tensors not right datatype - to doget datatypefrom tensor, can use `tensor.type`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`
    







In [ ]:
#crete a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.6507, 0.8229, 0.0727, 0.8773],
        [0.3979, 0.7468, 0.0167, 0.2951],
        [0.8444, 0.2376, 0.1843, 0.2238]])

In [ ]:
#find out details about some tensor
print(some_tensor)
print(f"Datatypes pf tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device Tensor is on:{some_tensor.device}")

tensor([[0.6507, 0.8229, 0.0727, 0.8773],
        [0.3979, 0.7468, 0.0167, 0.2951],
        [0.8444, 0.2376, 0.1843, 0.2238]])
Datatypes pf tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device Tensor is on:cpu


In [ ]:
some_tensor.size()

torch.Size([3, 4])

# Manupulating Tensors (tensor oprations)
Tensor oprations includes:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* MAtrix multiplication

In [ ]:
#create a tensor and 10 t0 it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor=tensor*10
tensor

tensor([10, 20, 30])

In [ ]:
tensor-5

tensor([ 5, 15, 25])

In [ ]:
torch.mul(tensor,2)

tensor([20, 40, 60])

In [ ]:
torch.add(tensor,55)

tensor([65, 75, 85])

### MATRIX MULTIPLICATION
Two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. MAtrix multiplication(dot Product)



In [ ]:
#element wise multiplication
print(tensor, "*",tensor)
print(f"Eqquals: {tensor * tensor}")

tensor([10, 20, 30]) * tensor([10, 20, 30])
Eqquals: tensor([100, 400, 900])


In [ ]:
#MAtrix Multiplication
torch.matmul(tensor,tensor)

tensor(1400)

In [ ]:
tensor=torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [ ]:
#matrix multiplication by hand
10*10 + 20*20 + 30*30

1400

In [ ]:
%%time
val = 0
for i in range(len(tensor)):
  val += tensor[i] * tensor[i]
print(val)


tensor(14)
CPU times: user 2.3 ms, sys: 872 µs, total: 3.17 ms
Wall time: 3.85 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 68 µs, sys: 13 µs, total: 81 µs
Wall time: 85.1 µs


tensor(14)

# Matrix Multiplication
1. **inner Dimesnsion must match:**
*  `(3,2) @ (2,4)` will work
*  `(3,4) @ (4,1)` will work
2. the resulting matrix has the shape of the **outer dimensions:**
* `(3,2) @ (2,4)`->`(3,4)`
* `(3,4) @ (4,1)` -> `(3,1)`

In [ ]:
torch.matmul(torch.rand(10,10),torch.rand(10,10)).shape

torch.Size([10, 10])

### One of the most common errors in deep learing: shape errors

In [ ]:
#shape for matrix multiplication

A = torch.tensor([[1,2],
                  [3,4],
                  [5,6]])

B = torch.tensor([[7,10],
                  [8,11]])

torch.mm(A, B) #torch.mm is the same as torch.matmul (it's an alia0s for writting less code)

tensor([[ 23,  32],
        [ 53,  74],
        [ 83, 116]])

In [ ]:
B.shape

torch.Size([2, 2])

In [ ]:
#Transpose
B.T,B

(tensor([[ 7,  8],
         [10, 11]]),
 tensor([[ 7, 10],
         [ 8, 11]]))

In [ ]:

A = torch.tensor([[1,2],
                  [3,4],
                  [5,6]])

B = torch.tensor([[7,10],
                  [8,11],[3,3]])

In [ ]:

print(f"Orignal shaps: A = {A.shape}, tensor_B = {B.shape}")
print(f"New shape after transpose A = {A.shape} tensor B = {B.T.shape}")
print(f"Multiplying: {A.shape} @ {B.T.shape}  <- inner dimension must be same")
print("output:\n")
x=torch.mm(A,B.T)
print(x)
print(f"Output shape: {x.shape}")

Orignal shaps: A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shape after transpose A = torch.Size([3, 2]) tensor B = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3])  <- inner dimension must be same
output:

tensor([[ 27,  30,   9],
        [ 61,  68,  21],
        [ 95, 106,  33]])
Output shape: torch.Size([3, 3])


### Finding the min, max, sum, etc(tensor aggrication)

In [ ]:
x=torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
#find the mean : Note--> the torch.mean() function  req a tensor of float32 datatype
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
#find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

##Finding the positional min and max

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:

## to find position ot index of min val in tensor
x.argmin()

tensor(0)

In [ ]:
x[0]

tensor(0)

In [ ]:
##same for max
x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(90)

##Reshapeing, stacking, squeezing and unsqueezing tensors
* Reshaping - reshapesan inut tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side(hstack)
* Squeeze - remove all `1` dimension from a tensor
* Unsqueeze - and a `1` dimension to a target tensor
* Permute - return a view of the input with dimention permuted(swapped) in a certain way

In [ ]:
#Let's  create tensor
import torch
x=torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
#add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# y_reshaped = x.reshape(3,3)
# y_reshaped, y_reshaped.shape

In [ ]:
#change the view
z=x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
##Changing z changes x (becuase a view of a tensor shares the same memory as the original input)
z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
#Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_reshaped.shape

torch.Size([1, 9])

In [ ]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x_reshaped.squeeze().shape

torch.Size([9])

In [ ]:
#torch.squeeze() - remove all single dimensions from a target tensor
print(f"Privous tensor: {x_reshaped}")
print(f"Privous tensor shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed =  x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New tensor shape: {x_squeezed.shape}")

Privous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Privous tensor shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New tensor shape: torch.Size([9])


In [ ]:
#torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim
print(f"Privious tensor: {x_squeezed}")
print(f"Privious shape: {x_squeezed.shape}")

#Add  an extra dimenstion with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f"\n New tensor: {x_unsqueezed}")
print(f"\n New shape: {x_unsqueezed.shape}")

Privious tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Privious shape: torch.Size([9])

 New tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

 New shape: torch.Size([9, 1])


##Torch.Permute

In [ ]:
  #torch.permute rearrange the dimensions of a target tensor in a specified order
  x_original = torch.rand(size=(224,224,3))

  #permute the original tensor to rearrange the axis (or dim) order
  x_permuted = x_original.permute(2, 0, 1) #shift axis 0->1, 1->2 2->0

  print(f"Privious shape: {x_original.shape}")
  print(f"New shape: {x_permuted.shape}")#[colour_channels, height, width]

Privious shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [ ]:
x_original[0,:,:]

tensor([[2.3316e-01, 7.0361e-01, 6.1178e-01],
        [3.4909e-01, 1.4262e-01, 8.1884e-01],
        [4.0094e-01, 3.6650e-01, 2.6719e-02],
        [5.7561e-01, 6.5303e-02, 2.9995e-01],
        [3.2409e-02, 1.7230e-01, 4.6504e-01],
        [6.8342e-01, 5.5308e-02, 8.8333e-01],
        [4.2990e-01, 5.2147e-01, 8.1470e-01],
        [9.6189e-01, 4.3490e-01, 5.4499e-01],
        [9.1132e-01, 8.4438e-01, 9.9984e-01],
        [8.5307e-01, 2.9380e-01, 6.0380e-01],
        [1.3665e-01, 9.4527e-02, 1.3516e-01],
        [9.3555e-01, 5.3728e-01, 3.0758e-01],
        [7.5330e-01, 9.6091e-01, 9.5253e-02],
        [2.2277e-01, 4.4904e-01, 6.1881e-01],
        [6.2373e-01, 8.4718e-01, 4.3422e-01],
        [3.2326e-01, 4.9639e-01, 9.9610e-01],
        [9.3944e-01, 4.9680e-02, 7.4537e-01],
        [3.4350e-01, 6.2260e-01, 4.8557e-01],
        [2.7003e-01, 7.4589e-02, 3.9336e-01],
        [6.3501e-01, 2.9892e-01, 3.2318e-01],
        [5.4603e-01, 5.1100e-01, 5.2224e-01],
        [2.1755e-01, 9.1637e-01, 7

In [ ]:
x_original[0,0,0] = 728218
x_original[0,0,0],x_permuted[0,0,0]

(tensor(728218.), tensor(728218.))

In [ ]:
x_original.shape

torch.Size([224, 224, 3])

#Indexing(selecting data from tensors)
indexing with PyTorch is similar to indexing with Numpy

In [2]:
import torch
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [3]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [4]:
x[0][0]

tensor([1, 2, 3])

In [5]:
x[0][0][0]

tensor(1)

In [7]:
x[0][2][2]

tensor(9)

In [8]:
x[:,:,0]

tensor([[1, 4, 7]])

In [9]:
x[:,0]

tensor([[1, 2, 3]])

In [10]:
x[:,:,:]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [11]:
x[:,1]

tensor([[4, 5, 6]])

#Pytorch tensors and numpy
numpy is a popular scentific python numerical computing library
beacuaseof this , it can intrect with pytorch tensors.


1.   Data in Numpy want in pytorch sensors -> *torch.from_numpy(ndarray)*
2.   pyTorch tensor  - > Numpy -> *torch.Tensors.numpy()*



In [14]:
#Numpy array to tensor
import torch
import numpy as np

arr = np.arange(1.0,8.0)
tensor = torch.from_numpy(arr) #warning: when convering from numpy -> pytorch, pytorch reflects numpy's defualt datatype of float64 unless specified otherwise
arr, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [15]:
tensor.dtype

torch.float64

In [16]:
arr.dtype

dtype('float64')

In [17]:
#change the value of array , it does not affect tensor
arr = arr + 1
arr, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [18]:
#tensors to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [20]:
numpy_tensor.dtype

dtype('float32')

In [21]:
#now when we chnage tensor,it does not change numpy
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# Reproducibility(trying to take random out of random)
In short how a NN lerans:

`start with random numbers -> tensors oprations -> updata random numbers to try and make them of the data -> again ->again-> agian...`

To reduce the randomness in NN and Pytorch comes the concept of a random of a **random seed**

Essentially what the random seed does is  "flavor" the randomness



In [22]:
torch.rand(3,3)

tensor([[0.1005, 0.9185, 0.8068],
        [0.0975, 0.1350, 0.8074],
        [0.6622, 0.6949, 0.9055]])

In [24]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
# print(random_tensor_A == random_tensor_B)

tensor([[0.0774, 0.6442, 0.9440, 0.2452],
        [0.0352, 0.6466, 0.1063, 0.8990],
        [0.8413, 0.1890, 0.0428, 0.4965]])
tensor([[0.2514, 0.8248, 0.1786, 0.3051],
        [0.2433, 0.4422, 0.9102, 0.5608],
        [0.9771, 0.7899, 0.3676, 0.1160]])


In [25]:

#let's make some random but reproducible tensors

import torch

#set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra resorce of reproduciblity:
* https://pytorch.org/docs/stable/notes/randomness.html
* https://pytorch.org/docs/stable/notes/randomness.html