<a href="https://colab.research.google.com/github/devanshi311/Pytorch-Learning/blob/main/03_day_pytorchLearing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Running tensors and Pytorch objects on the GPUs(and makingfaster computations)
GPUs = faster computations on numbers, thanks to CUDA _NVIDIA hardware +Pytorch working behind the scenes to make everything noice.

In [1]:
!nvidia-smi

Wed Feb 21 06:18:52 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   64C    P8              11W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

#check for GPU acces with PyTorch

In [5]:
import torch
torch.cuda.is_available()

True

In [7]:
#Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device


'cuda'

In [8]:
#Count Number of devices
print(torch.cuda.device_count(

))

1


# Putting tensors (and models) on the GPU
the reason we want out tensors/models on the GPU is beacuase using GPU results in faster compuataions

In [9]:
#Create  atensor (defualt on the CPU)
tensor = torch.tensor([1,2,3])

#tensor not on GPU
print(tensor, tensor.device)


tensor([1, 2, 3]) cpu


In [11]:
#Move tensor to GPU(if avilable)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

#Moving tensors back to the GPU

In [14]:
#if tensor is on GPU, can't tranforms it to Numpy
# tensor_on_gpu.numpy()


In [15]:
#To fix the GPU tensor with Numpy issue ,we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [16]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')